"use client";

import Image from "next/image";
import Link from "next/link";
import Navbar from "../../../../components/Navbar";
import Contact from "../../../../components/Contact";
import { useLanguage } from "../../../../components/LanguageProvider";

const creativeStack = ["Figma", "Branding", "Graphic Design", "AI Visuals", "Sports Media", "Social Media", "Video Editing"];
const activities = ["Basketball", "Badminton", "HYROX", "Fitness", "Yoga", "Friidrett", "Orientering", "Senior", "Mor & baby", "Fjellveidager"];

export default function VareggArenaCaseStudy() {
  const { language } = useLanguage();
  const no = language === "no";

  return (
    <main className="min-h-screen bg-black text-white">
      <Navbar />
      <section className="relative overflow-hidden px-6 pb-20 pt-36 md:pt-44">
        <div className="pointer-events-none absolute left-1/2 top-20 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-red-600/10 blur-[150px]" />
        <div className="relative mx-auto max-w-7xl">
          <Link href="/Projects" className="text-sm font-medium text-white/60 transition hover:text-white">← {no ? "Tilbake til prosjekter" : "Back to projects"}</Link>
          <div className="mt-9 max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[0.32em] text-red-300/80">{no ? "Case study · Kreativt visuelt · 2025–2026" : "Case study · Creative visual · 2025–2026"}</p><h1 className="mt-5 text-5xl font-bold tracking-tight md:text-8xl">Varegg Arena</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/75 md:text-xl">{no ? "Et omfattende visuelt prosjekt med sportsbilder, kampanjemateriell, bannere, plakater, eventgrafikk og video — utviklet for mange ulike aktiviteter og målgrupper." : "A broad visual project spanning sports imagery, campaign material, banners, posters, event graphics and video — created for many different activities and audiences."}</p></div>
          <div className="relative mt-14 aspect-[16/7] overflow-hidden rounded-4xl border border-white/15 bg-zinc-950 shadow-2xl"><video src="/projects/Varegg-Arena/perimeter.mov" autoPlay muted loop playsInline preload="metadata" className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-black/10" /><div className="absolute bottom-6 left-6 md:bottom-10 md:left-10"><p className="text-xs uppercase tracking-[0.3em] text-white/60">Visual direction</p><p className="mt-2 text-2xl font-bold md:text-4xl">Sport · Energy · Community</p></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-12"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl border border-red-300/15 bg-red-400/[0.04] p-7"><p className="text-xs uppercase tracking-[0.28em] text-white/50">{no ? "Min rolle" : "My role"}</p><p className="mt-4 text-xl font-semibold">Design · Branding · Creative</p></div><div className="rounded-3xl border border-white/15 bg-white/[0.04] p-7"><p className="text-xs uppercase tracking-[0.28em] text-white/50">{no ? "Leveranser" : "Deliverables"}</p><p className="mt-4 text-xl font-semibold">Visuals · Posters · Banners · Video</p></div><div className="rounded-3xl border border-white/15 bg-white/[0.04] p-7"><p className="text-xs uppercase tracking-[0.28em] text-white/50">{no ? "Fokus" : "Focus"}</p><p className="mt-4 text-xl font-semibold">Sport · Events · Promotion</p></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-16"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.3em] text-red-300/75">01 · {no ? "Utfordringen" : "The challenge"}</p><h2 className="mt-4 text-4xl font-bold">{no ? "Mange aktiviteter. Ett visuelt univers." : "Many activities. One visual universe."}</h2></div><p className="text-lg leading-9 text-white/72">{no ? "Varegg Arena kommuniserer mange ulike aktiviteter til mennesker i forskjellige aldre. Oppgaven har derfor handlet om å skape visuelt materiale som kan tilpasses alt fra HYROX og basketball til yoga, seniortrening, orientering og familieaktiviteter — samtidig som uttrykket føles energisk og gjenkjennelig." : "Varegg Arena communicates a wide range of activities to people of different ages. The work therefore required visual material that could adapt from HYROX and basketball to yoga, senior training, orienteering and family activities while retaining an energetic and recognizable expression."}</p></div>
        <div className="mt-12 flex flex-wrap gap-3">{activities.map((item) => <span key={item} className="rounded-full border border-white/15 bg-white/[0.05] px-4 py-2 text-sm text-white/75">{item}</span>)}</div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-5 md:grid-cols-12"><div className="relative min-h-[420px] overflow-hidden rounded-4xl border border-white/15 md:col-span-8"><Image src="/projects/Varegg-Arena/perimeter.png" alt="Varegg Arena visual work" fill sizes="(max-width: 768px) 100vw, 66vw" className="object-cover" /></div><div className="flex min-h-[420px] flex-col justify-end rounded-4xl border border-red-300/15 bg-gradient-to-br from-red-500/[0.12] to-zinc-950 p-8 md:col-span-4"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-red-300/75">02 · Visual direction</p><h2 className="mt-4 text-3xl font-bold">{no ? "Cinematisk energi" : "Cinematic energy"}</h2><p className="mt-5 leading-7 text-white/70">{no ? "Mørke bakgrunner, tydelig lyssetting, bevegelse, partikler og sterke sportsøyeblikk brukes for å gi materialet mer energi og dybde, samtidig som motivet og aktiviteten er lett å forstå." : "Dark backgrounds, defined lighting, movement, particles and strong sporting moments give the material energy and depth while keeping the activity easy to understand."}</p></div></div></section>

      <section className="mx-auto grid max-w-7xl gap-8 px-6 py-20 lg:grid-cols-2"><article className="rounded-4xl border border-white/15 bg-white/[0.04] p-8 md:p-10"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-red-300/75">03 · {no ? "Designprosessen" : "Design process"}</p><h2 className="mt-4 text-3xl font-bold">{no ? "Fra idé til ferdig kampanjemateriell" : "From idea to finished campaign material"}</h2><p className="mt-5 text-base leading-8 text-white/72">{no ? "Arbeidet kombinerer idéutvikling, bildearbeid, AI-assisterte visualer, komposisjon, typografi, branding og tilpasning til ulike formater. Målet er ikke bare å lage enkeltbilder, men et fleksibelt visuelt uttrykk som fungerer på tvers av aktiviteter og kampanjer." : "The work combines concept development, image work, AI-assisted visuals, composition, typography, branding and adaptation to different formats. The goal is not simply to create individual images, but a flexible visual language that works across activities and campaigns."}</p></article><article className="rounded-4xl border border-white/15 bg-white/[0.04] p-8 md:p-10"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-red-300/75">04 · {no ? "Resultatet" : "The result"}</p><h2 className="mt-4 text-3xl font-bold">{no ? "Et prosjekt som viser kreativ bredde" : "A project that shows creative range"}</h2><p className="mt-5 text-base leading-8 text-white/72">{no ? "Varegg Arena viser en annen side av arbeidet mitt enn de rene frontend-prosjektene. Her kombinerer jeg design, visuell historiefortelling, sportsprofilering og digital produksjon i materiale som kan brukes til arrangementer, aktiviteter og markedsføring." : "Varegg Arena shows a different side of my work from the pure frontend projects. Here I combine design, visual storytelling, sports communication and digital production in material for events, activities and promotion."}</p></article></section>

      <section className="mx-auto max-w-7xl px-6 pb-24"><div className="rounded-4xl border border-red-300/15 bg-gradient-to-br from-red-500/[0.1] via-white/[0.03] to-transparent p-8 md:p-12"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-white/55">Creative stack</p><div className="mt-6 flex flex-wrap gap-3">{creativeStack.map((item) => <span key={item} className="rounded-full border border-white/15 bg-black/30 px-4 py-2 text-sm text-white/85">{item}</span>)}</div><div className="mt-12 flex flex-wrap items-center justify-between gap-5 border-t border-white/10 pt-8"><div><p className="text-sm text-white/55">{no ? "Tilbake til oversikten" : "Back to overview"}</p><p className="mt-1 text-2xl font-bold">{no ? "Se flere prosjekter" : "Explore more projects"}</p></div><Link href="/Projects" className="rounded-full border border-white/20 bg-white/[0.07] px-6 py-3 font-semibold transition hover:bg-white/[0.14]">{no ? "Alle prosjekter →" : "All projects →"}</Link></div></div></section>
      <Contact />
    </main>
  );
}
