"use client";

import { useState } from "react";
import Image from "next/image";
import { Settings } from "lucide-react";
import Navbar from "../../../components/Navbar";
import Contact from "../../../components/Contact";
import { useLanguage } from "../../../components/LanguageProvider";

const matrixColumns = Array.from({ length: 16 }, (_, index) => index);
const musicVideos = ["/media/Far From Me.mp4", "/media/Set the Dark on Fire.mp4", "/media/Hungry Touch.mp4", "/media/Halfway up.mp4", "/media/final night.mp4", "/media/Enter the dragon.mp4", "/media/Light breaks through the night.mp4"];

type Project = { title: string; description: string; descriptionNo: string; image: string; tech: string[]; github: string; demo: string; year?: string; video?: string; underConstruction?: boolean; };

const developmentProjects: Project[] = [
  { title: "Bergen Stupeklubb", year: "2026", description: "A modern, accessible and responsive website for Bergen Stupeklubb, designed to help visitors explore diving activities, courses, club information and registration.", descriptionNo: "En moderne, tilgjengelig og responsiv nettside for Bergen Stupeklubb, laget for å gjøre det enkelt å utforske stuping, kurs, klubbinformasjon og påmelding.", image: "/projects/stupeklubb.png", tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Responsive Design", "Accessibility", "Vercel"], github: "https://github.com/PMariusf/bergen-stupeklubb", demo: "https://bergen-stupeklubb-r7xd.vercel.app/" },
  { title: "House of Mambo", year: "2026", description: "A modern and visually engaging dance website for House of Mambo, combining responsive frontend development, strong visual identity and accessibility-focused improvements.", descriptionNo: "En moderne og visuelt engasjerende dansenettside for House of Mambo, med responsiv frontend-utvikling, sterk visuell identitet og fokus på tilgjengelighet.", image: "/projects/mambo.png", tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Responsive Design", "Accessibility", "Vercel"], github: "#", demo: "https://house-of-mambo.vercel.app/" },
  { title: "Foyner", year: "2026", description: "A modern photography portfolio built with Next.js, React and Tailwind CSS, focusing on elegant typography, responsive layouts and smooth user interactions.", descriptionNo: "En moderne fotoportfolio bygget med Next.js, React og Tailwind CSS, med fokus på elegant typografi, responsive layouter og smidige brukerinteraksjoner.", image: "/projects/foyner-page.png", tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Responsive Design", "Vercel"], github: "https://github.com/PMariusf/foyner", demo: "https://www.foyner.no/" },
  { title: "Nordhordaland Kampsport", year: "2026", description: "A modern and responsive website for Nordhordaland Kampsport, designed to make it easy for visitors to explore the club, view martial arts activities, find training schedules and access membership information.", descriptionNo: "En moderne og responsiv nettside for Nordhordaland Kampsport, laget for enkel tilgang til informasjon om klubben, kampsporttilbud, treningstider og medlemskap.", image: "/projects/nordhordaland-kampsport.png", tech: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Responsive Design", "Vercel", "Visual Image Creation"], github: "#", demo: "https://norhordaland-kampsport.vercel.app" },
  { title: "Solar System Explorer", year: "2026", description: "An immersive 3D Solar System experience built with Next.js, React Three Fiber and Three.js. Explore the planets through interactive scenes, realistic animations and educational content while showcasing modern frontend technologies.", descriptionNo: "En interaktiv 3D-opplevelse av solsystemet bygget med Next.js, React Three Fiber og Three.js. Utforsk planetene gjennom interaktive scener, realistiske animasjoner og lærerikt innhold.", image: "/projects/Solarsystem.png", tech: ["Next.js", "React", "TypeScript", "Three.js", "React Three Fiber", "Tailwind CSS", "GLTF Models", "Vercel"], github: "https://github.com/PMariusf/solsystem", demo: "https://solsystem-peach.vercel.app" },
  { title: "Fjellveidager Design", year: "2026", description: "Creative branding, posters and event visuals for Fjellveidager, including logo work and promotional graphics.", descriptionNo: "Kreativ profilering, plakater og visuelt innhold for Fjellveidager, inkludert logoarbeid og grafikk til markedsføring.", image: "/projects/Varegg-Arena/fjellveidager.png", tech: ["Figma", "Design", "Branding", "React", "Next.js", "Tailwind", "VSCode", "Vercel", "GitHub", "Video Editing"], github: "https://github.com/PMariusf/fjellveidager-no", demo: "#" },
  { title: "Aivento", year: "2025", description: "Modern responsive website built with Squarespace, focused on clean design, layout and visual communication.", descriptionNo: "Moderne responsiv nettside bygget med Squarespace, med fokus på rent design, layout og visuell kommunikasjon.", image: "/projects/Varegg-Arena/Aivento.png", tech: ["Figma", "Design", "Squarespace", "VSCode", "Vercel", "GitHub", "Video Editing"], github: "#", demo: "https://www.aivento.no/" },
  { title: "PM Portfolio", description: "A modern portfolio experience combining frontend development, creative design and interactive UI — built with Next.js, React and Tailwind CSS.", descriptionNo: "En moderne portfolio som kombinerer frontend-utvikling, kreativt design og interaktivt brukergrensesnitt — bygget med Next.js, React og Tailwind CSS.", image: "/projects/music.png", tech: ["React", "Next.js", "Tailwind", "VSCode", "Vercel", "GitHub"], github: "https://github.com/PMariusf/PMs-Portfolio", demo: "#" },
  { title: "Future project", description: "Clean frontend webpage focused on layout, design and user experience.", descriptionNo: "Ren frontend-side med fokus på layout, design og brukeropplevelse.", image: "/projects/web-project-two.png", tech: ["React", "Tailwind", "UI/UX", "Frontend", "Responsive Design"], github: "#", demo: "#", underConstruction: true },
];

const creativeProjects: Project[] = [
  { title: "Varegg Arena", year: "2025–2026", description: "Creative design and branding work for Varegg Arena, including sports visuals, event graphics, banners, posters and promotional content for multiple activities such as basketball, badminton, HYROX, fitness and Fjellveidager.", descriptionNo: "Kreativt design- og profileringsarbeid for Varegg Arena, inkludert sportsvisualer, arrangementsgrafikk, bannere, plakater og markedsmateriell for blant annet basketball, badminton, HYROX, fitness og Fjellveidager.", image: "/projects/Varegg-Arena/perimeter.png", video: "/projects/Varegg-Arena/perimeter.mov", tech: ["Figma", "Branding", "Design", "AI Visuals", "Social Media", "Video Editing"], github: "#", demo: "#" },
  { title: "AdO Arena", year: "2026", description: "Cinematic arena visuals, water, diving and event promotion created for AdO Arena.", descriptionNo: "Cinematiske arenavisualer, vann, stuping og arrangementsprofilering laget for AdO Arena.", image: "/projects/ado-arena/ado.png", video: "/projects/ADO.mov", tech: ["Design", "AI Visuals", "Video Editing", "Event Promo", "Branding"], github: "#", demo: "#" },
  { title: "Åsane Arena", year: "2026", description: "Sports arena visuals, branding and creative promotional content for Åsane Arena.", descriptionNo: "Sportsvisualer, profilering og kreativt markedsmateriell for Åsane Arena.", image: "/projects/Varegg-Arena/Asanearena.png", tech: ["Design", "Branding", "AI Visuals", "Sports Media", "Promotion"], github: "#", demo: "#" },
  { title: "AI Music & Creative Projects", year: "2025–2026", description: "Creative music production using Suno AI, cinematic sound design, custom lyrics, EDM, Eurodance, soft rock and experimental music creation. Also includes AI visuals, image editing and creative digital concepts.", descriptionNo: "Kreativ musikkproduksjon med Suno AI, cinematisk lyddesign, egne sangtekster, EDM, Eurodance, softrock og eksperimentell musikk. Inkluderer også AI-visualer, bilderedigering og kreative digitale konsepter.", image: "/projects/music.png", tech: ["Suno AI", "Music Production", "AI", "Creative Design", "Audio"], github: "#", demo: "https://suno.com" },
];

export default function ProjectsPage() {
  const [currentMusic, setCurrentMusic] = useState(0);
  const { language } = useLanguage();
  const no = language === "no";

  const renderProject = (project: Project) => (
    <div key={project.title} className="overflow-hidden rounded-4xl border border-white/20 bg-white/10 shadow-2xl backdrop-blur-xl transition duration-300 hover:-translate-y-2">
      <div className="grid md:grid-cols-2">
        <div className="relative flex h-80 items-center justify-center overflow-hidden bg-black">
          {project.title === "PM Portfolio" ? <div className="absolute inset-0 bg-black"><div className="matrix-rain opacity-80">{matrixColumns.map((column) => <span key={column} className={`matrix-column matrix-column-${column}`}>{"01 PM NEXT REACT TAILWIND CODE ".repeat(8)}</span>)}</div><div className="absolute inset-0 bg-linear-to-t from-black via-transparent to-black/40"/><div className="absolute inset-0 flex items-center justify-center"><h3 className="text-center text-3xl font-bold uppercase tracking-[0.45em]">PM PORTFOLIO</h3></div></div> : project.title === "AI Music & Creative Projects" ? <div className="relative h-full w-full"><video key={musicVideos[currentMusic]} src={musicVideos[currentMusic]} muted loop playsInline controls preload="metadata" className="h-full w-full object-contain"/><button onClick={() => setCurrentMusic(p => p === 0 ? musicVideos.length - 1 : p - 1)} className="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-black/60 px-4 py-2 text-2xl" aria-label={no ? "Forrige musikkvideo" : "Previous music video"}>‹</button><button onClick={() => setCurrentMusic(p => p === musicVideos.length - 1 ? 0 : p + 1)} className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-black/60 px-4 py-2 text-2xl" aria-label={no ? "Neste musikkvideo" : "Next music video"}>›</button><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2">{musicVideos.map((_, index) => <button key={index} onClick={() => setCurrentMusic(index)} className={`h-2 w-2 rounded-full ${currentMusic === index ? "bg-white" : "bg-white/40"}`} aria-label={`${no ? "Gå til musikkvideo" : "Go to music video"} ${index + 1}`}/>)}</div></div> : project.video ? <video src={project.video} autoPlay muted loop playsInline preload="metadata" className="max-h-full max-w-full object-contain"/> : <Image src={project.image} alt={project.title} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover"/>}
          {project.underConstruction && <div className="absolute inset-0 z-30 flex flex-col items-center justify-center gap-5 bg-black/70 backdrop-blur-md"><Settings className="h-16 w-16 animate-[spin_8s_linear_infinite] text-yellow-300"/><h3 className="text-center text-xl font-black uppercase tracking-[0.35em] text-yellow-300">{no ? "UNDER UTVIKLING" : "UNDER CONSTRUCTION"}</h3></div>}
        </div>
        <div className="p-8"><div className="flex items-start justify-between gap-5"><h2 className="text-3xl font-bold">{project.title}</h2>{project.year && <span className="shrink-0 pt-2 text-sm font-medium tracking-[0.2em] text-white/40">{project.year}</span>}</div><p className="mt-4 leading-relaxed text-white/70">{no ? project.descriptionNo : project.description}</p><div className="mt-5 flex flex-wrap gap-3">{project.tech.map((tech) => <span key={tech} className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm text-white/80">{tech}</span>)}</div><div className="mt-8 flex gap-4">{project.github !== "#" && <a href={project.github} target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/20 bg-white/10 px-5 py-3 transition hover:bg-white/20">GitHub</a>}{project.demo !== "#" && <a href={project.demo} target="_blank" rel="noopener noreferrer" className="rounded-full bg-white px-5 py-3 text-black transition hover:scale-105">{no ? "Se nettsiden" : "Live Demo"}</a>}</div></div>
      </div>
    </div>
  );

  return <main className="min-h-screen bg-black text-white"><Navbar/><section className="mx-auto max-w-7xl px-6 py-32"><p className="text-sm uppercase tracking-[0.4em] text-white/50">{no ? "Utvalgt arbeid" : "Selected Work"}</p><h1 className="mt-4 text-5xl font-bold">{no ? "Frontend, kreative & tekniske prosjekter" : "Frontend, Creative & Technical Projects"}</h1><p className="mt-6 max-w-3xl text-lg text-white/70">{no ? "En samling frontend-utvikling, kreative konsepter og tekniske prosjekter som viser design, interaktivitet og problemløsning." : "A collection of frontend development, creative concepts and technical projects showcasing design, interactivity and problem solving."}</p><div className="mt-14"><h2 className="mb-8 text-4xl font-bold">{no ? "Utvikling" : "Development"}</h2><div className="grid gap-8">{developmentProjects.map(renderProject)}</div></div><div className="mt-20 border-t border-white/10 pt-14"><h2 className="mb-8 text-4xl font-bold">{no ? "Kreativt visuelt" : "Creative Visual"}</h2><div className="grid gap-8">{creativeProjects.map(renderProject)}</div></div></section><Contact/></main>;
}
