"use client";

import Link from "next/link";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import Hero from "../../components/Hero";
import Interests from "../../components/Interests";
import Contact from "../../components/Contact";
import { Settings } from "lucide-react";
import { useLanguage } from "../../components/LanguageProvider";

const matrixColumns = Array.from({ length: 16 }, (_, index) => index);
const musicVideos = ["/media/Far From Me.mp4", "/media/Set the Dark on Fire.mp4", "/media/Halfway up.mp4", "/media/final night.mp4", "/media/Enter the dragon.mp4", "/media/Light breaks through the night.mp4"];
type GlowTone = "green" | "blue" | "amber" | "violet" | "purple" | "red" | "cyan" | "orange" | "neutral";
type HomeProject = { title: string; image: string; text: string; textNo?: string; year?: string; href?: string; external?: boolean; video?: string; underConstruction?: boolean; glow: GlowTone; };

const developmentProjects: HomeProject[] = [
  { title: "Bergen Stupeklubb", image: "/projects/stupeklubb.png", text: "Accessible and responsive sports club website built with Next.js, TypeScript and Tailwind CSS.", textNo: "Tilgjengelig og responsiv nettside for idrettsklubb, bygget med Next.js, TypeScript og Tailwind CSS.", year: "2026", href: "https://bergen-stupeklubb-r7xd.vercel.app/", external: true, glow: "cyan" },
  { title: "House of Mambo", image: "/projects/mambo.png", text: "Modern dance website with strong visual identity, responsive design and accessibility improvements.", textNo: "Moderne dansenettside med sterk visuell identitet, responsivt design og forbedret tilgjengelighet.", year: "2026", href: "https://house-of-mambo.vercel.app/", external: true, glow: "purple" },
  { title: "Foyner", image: "/projects/foyner-page.png", text: "Modern photography portfolio built with Next.js, React and Tailwind CSS.", textNo: "Moderne fotoportfolio bygget med Next.js, React og Tailwind CSS.", year: "2026", href: "https://www.foyner.no/", external: true, glow: "amber" },
  { title: "Nordhordaland Kampsport", image: "/projects/nordhordaland-kampsport.png", text: "Modern responsive club website built with Next.js, TypeScript and Tailwind CSS.", textNo: "Moderne og responsiv klubbside bygget med Next.js, TypeScript og Tailwind CSS.", year: "2026", href: "https://norhordaland-kampsport.vercel.app", external: true, glow: "green" },
  { title: "Solar System Explorer", image: "/projects/Solarsystem.png", text: "Interactive 3D Solar System built with React Three Fiber, Three.js and Next.js.", textNo: "Interaktivt 3D-solsystem bygget med React Three Fiber, Three.js og Next.js.", year: "2026", glow: "blue" },
  { title: "Fjellveidager", image: "/projects/Varegg-Arena/fjellveidager.png", text: "Creative branding, posters and event visuals.", textNo: "Kreativ profilering, plakater og visuelt innhold for arrangement.", year: "2026", glow: "amber" },
  { title: "Aivento", image: "/projects/Varegg-Arena/Aivento.png", text: "Modern responsive website built with Squarespace.", textNo: "Moderne responsiv nettside bygget med Squarespace.", year: "2025", glow: "violet" },
  { title: "PM-portfolio", image: "/projects/music.png", text: "Coding is Life.", textNo: "Kode er livet.", glow: "purple" },
  { title: "Future project", image: "/projects/web-project-two.png", text: "Clean frontend webpage focused on layout, design and user experience.", textNo: "Ren frontend-side med fokus på layout, design og brukeropplevelse.", underConstruction: true, glow: "neutral" },
];
const creativeProjects: HomeProject[] = [
  { title: "Varegg Arena", image: "/projects/Varegg-Arena/varegg.png", video: "/projects/Varegg-Arena/perimeter.mov", text: "Sports visuals, branding and event graphics.", textNo: "Sportsvisualer, profilering og grafikk for arrangement.", year: "2025–2026", glow: "red" },
  { title: "AdO Arena", image: "/projects/ado-arena/ado.png", video: "/projects/ADO.mov", text: "Cinematic arena visuals, water, diving and event promotion.", textNo: "Cinematiske arenavisualer, vann, stuping og arrangementsprofilering.", year: "2026", glow: "cyan" },
  { title: "Åsane Arena", image: "/projects/Varegg-Arena/Asanearena.png", text: "Sports arena visuals, branding and creative promotional content.", textNo: "Visuelt innhold for sportsarena, profilering og kreativt markedsmateriell.", year: "2026", glow: "blue" },
  { title: "Creative Music", image: "/projects/music.png", video: musicVideos[0], text: "AI music production, cinematic sound design and creative media.", textNo: "AI-musikkproduksjon, cinematisk lyddesign og kreative medier.", year: "2025–2026", glow: "orange" },
];
const glowStyles: Record<GlowTone,string> = { green:"hover:border-emerald-300/25 hover:shadow-[0_24px_70px_rgba(16,185,129,0.18)]", blue:"hover:border-blue-300/25 hover:shadow-[0_24px_70px_rgba(59,130,246,0.18)]", amber:"hover:border-amber-300/25 hover:shadow-[0_24px_70px_rgba(245,158,11,0.16)]", violet:"hover:border-violet-300/25 hover:shadow-[0_24px_70px_rgba(139,92,246,0.17)]", purple:"hover:border-fuchsia-300/25 hover:shadow-[0_24px_70px_rgba(168,85,247,0.2)]", red:"hover:border-red-300/25 hover:shadow-[0_24px_70px_rgba(239,68,68,0.18)]", cyan:"hover:border-cyan-300/25 hover:shadow-[0_24px_70px_rgba(34,211,238,0.2)]", orange:"hover:border-orange-300/25 hover:shadow-[0_24px_70px_rgba(249,115,22,0.2)]", neutral:"hover:border-white/20 hover:shadow-[0_24px_70px_rgba(255,255,255,0.08)]" };
const gradientStyles: Record<GlowTone,string> = { green:"from-emerald-400/10 via-transparent to-black/80",blue:"from-blue-400/10 via-transparent to-black/80",amber:"from-amber-400/10 via-transparent to-black/80",violet:"from-violet-400/10 via-transparent to-black/80",purple:"from-fuchsia-400/10 via-transparent to-black/80",red:"from-red-400/10 via-transparent to-black/80",cyan:"from-cyan-400/10 via-transparent to-black/80",orange:"from-orange-400/10 via-transparent to-black/80",neutral:"from-white/5 via-transparent to-black/80" };

function ProjectCard({ project, language }: { project: HomeProject; language: "no" | "en" }) { return <Link href={project.href ?? "/Projects"} target={project.external ? "_blank" : undefined} rel={project.external ? "noopener noreferrer" : undefined} className={`group relative block h-full overflow-hidden rounded-3xl border border-white/10 bg-black/35 shadow-[0_18px_50px_rgba(0,0,0,0.38)] backdrop-blur-xl transition duration-500 hover:bg-white/[0.07] ${glowStyles[project.glow]}`}><div className="relative h-44 overflow-hidden bg-black">{project.title === "PM-portfolio" ? <div className="absolute inset-0 bg-black"><Image src={project.image} alt={project.title} fill sizes="33vw" className="object-cover opacity-35"/><div className="matrix-rain opacity-75">{matrixColumns.map(c=><span key={c} className={`matrix-column matrix-column-${c}`}>{"01 PM NEXT REACT TAILWIND CODE ".repeat(8)}</span>)}</div><div className="absolute inset-0 flex items-center justify-center"><h3 className="text-center text-2xl font-bold uppercase tracking-[0.45em]">PM PORTFOLIO</h3></div></div> : project.video ? <video src={project.video} autoPlay muted loop playsInline className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.04]"/> : <Image src={project.image} alt={project.title} fill sizes="(max-width: 768px) 100vw, 33vw" priority={project.title === "Bergen Stupeklubb" || project.title === "House of Mambo"} className="object-cover transition-transform duration-700 group-hover:scale-[1.04]"/>}<div className={`pointer-events-none absolute inset-0 bg-linear-to-br ${gradientStyles[project.glow]} opacity-75`}/>{project.underConstruction && <div className="absolute inset-0 z-20 flex flex-col items-center justify-center gap-5 bg-black/60 backdrop-blur-md"><Settings className="h-10 w-10 animate-[spin_8s_linear_infinite] text-yellow-300"/><h2 className="text-center text-lg font-black uppercase tracking-[0.3em] text-yellow-300">{language === "no" ? "UNDER UTVIKLING" : "UNDER CONSTRUCTION"}</h2></div>}</div><div className="relative z-20 bg-linear-to-b from-white/[0.055] to-white/[0.018] p-5"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-bold">{project.title}</h3>{project.year && <span className="text-xs tracking-[0.18em] text-white/40">{project.year}</span>}</div><p className="mt-2 text-sm font-semibold leading-relaxed text-white/70">{language === "no" ? project.textNo ?? project.text : project.text}</p><p className="mt-4 text-sm font-bold text-white/80">{project.external ? (language === "no" ? "Besøk nettsiden →" : "Visit live site →") : (language === "no" ? "Se prosjekt →" : "View project →")}</p></div></Link> }
function ProjectGrid({ projects, language }: { projects: HomeProject[]; language: "no" | "en" }) { return <div className="grid gap-0 md:grid-cols-2 lg:grid-cols-4">{projects.map((p,i)=><div key={p.title} className={`border-white/10 p-4 sm:p-5 ${i>0?"border-t":""} ${i>=2?"md:border-t":"md:border-t-0"} ${i%2?"md:border-l":""} ${i>=4?"lg:border-t":"lg:border-t-0"} ${i%4?"lg:border-l":"lg:border-l-0"}`}><ProjectCard project={p} language={language}/></div>)}</div> }
function SectionDivider(){return <div className="flex items-center justify-center py-16"><div className="h-px w-1/2 max-w-2xl bg-linear-to-r from-transparent via-white/25 to-transparent"/></div>}

export default function Home(){ const { language }=useLanguage(); const no=language==="no"; const freelanceServices=no?[{number:"01",title:"Nettsideutvikling",text:"Moderne, responsive nettsider med Next.js, React og Tailwind CSS — fra idé til lansering."},{number:"02",title:"Redesign & modernisering",text:"Gi en eksisterende nettside et renere uttrykk, bedre mobilopplevelse og et mer moderne grensesnitt."},{number:"03",title:"Design & visuelt innhold",text:"Webdesign, Figma-konsepter og visuelt innhold som gir prosjektet en tydelig og helhetlig identitet."},{number:"04",title:"Ytelse & tilgjengelighet",text:"Forbedring av lastetid, Lighthouse-resultater, responsivitet og tilgjengelighet."}]:[{number:"01",title:"Website Development",text:"Modern, responsive websites built with Next.js, React and Tailwind CSS — from idea to launch."},{number:"02",title:"Redesign & Modernization",text:"Give an existing website a cleaner look, stronger mobile experience and more modern user interface."},{number:"03",title:"Design & Visual Content",text:"Web design, Figma concepts and visual content that gives your project a clear and consistent identity."},{number:"04",title:"Performance & Accessibility",text:"Improve loading speed, Lighthouse scores, responsive behavior and accessibility across devices."}]; return <main className="min-h-screen bg-black text-white"><div className="fixed inset-0 bg-black"/><div className="relative z-10"><Navbar/>
<section className="fade-up mx-auto max-w-[95%] pt-28"><div className="overflow-hidden rounded-4xl border border-white/10 bg-white/4 shadow-2xl backdrop-blur-xl"><div className="grid items-center gap-10 p-6 lg:grid-cols-2 lg:p-14"><div className="relative flex items-center justify-center overflow-hidden rounded-4xl border border-white/10 bg-black/40 p-4"><div className="-translate-y-20 scale-100"><Hero/></div></div><div><p className="text-sm uppercase tracking-[0.4em] text-white/50">Frontend Developer</p><h1 className="mt-5 text-5xl font-bold leading-tight md:text-7xl">{no?"Moderne webdesign med en kreativ kant":"Modern Web Design with a Creative Edge"}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/70">{no?"Jeg bygger moderne, responsive og visuelt engasjerende nettsider med React, Next.js og Tailwind CSS — med stor interesse for design, AI og kreative digitale opplevelser.":"I build modern, responsive and visually engaging websites using React, Next.js and Tailwind CSS — with a strong interest in design, AI and creative digital experiences."}</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/Projects" className="rounded-full bg-white px-6 py-3 font-medium text-black transition hover:scale-105">{no?"Se prosjekter":"View Projects"}</Link><Link href="/About" className="rounded-full border border-white/20 bg-white/10 px-6 py-3 font-medium text-white transition hover:bg-white/20">{no?"Om meg":"About Me"}</Link></div><p className="mt-5 text-sm uppercase tracking-[0.25em] text-white/55">{no?"Tilgjengelig for praksis / frontend-muligheter":"Available for internship / frontend opportunities"}</p></div></div></div></section>
<section className="fade-up mx-auto max-w-7xl px-6 pt-20"><div className="rounded-4xl border border-white/10 bg-white/4 p-6 shadow-2xl backdrop-blur-xl md:p-10"><div className="mb-14 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[0.4em] text-white/60">{no?"Kreativt utvalg":"Creative Showcase"}</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">{no?"Frontend, design & visuelle prosjekter":"Frontend, Design & Visual Projects"}</h2><p className="mt-4 max-w-2xl text-white/60">{no?"Et utvalg frontend-utvikling, kreative visualer, digital kunst og personlige prosjekter som viser interessen min for teknologi og design.":"A collection of frontend development, creative visuals, digital art and personal projects that reflect my passion for technology and design."}</p></div><Link href="/Projects" className="w-fit rounded-full border border-white/20 bg-white/10 px-5 py-3 text-white/70 transition hover:bg-white/20 hover:text-white">{no?"Se alle prosjekter":"View all projects"}</Link></div><div><div className="mb-8"><p className="text-xs uppercase tracking-[0.38em] text-white/40">{no?"Utvalgt arbeid":"Selected work"}</p><h3 className="mt-2 text-4xl font-bold md:text-5xl">Utvikling</h3></div><ProjectGrid projects={developmentProjects} language={language}/></div><SectionDivider/><div><div className="mb-8"><p className="text-xs uppercase tracking-[0.38em] text-white/40">{no?"Design & media":"Design & media"}</p><h3 className="mt-2 text-4xl font-bold md:text-5xl">{no?"Kreativt visuelt":"Creative Visual"}</h3></div><ProjectGrid projects={creativeProjects} language={language}/></div></div></section>
<section className="fade-up mx-auto max-w-7xl px-6 pt-20"><div className="relative overflow-hidden rounded-4xl border border-white/10 bg-white/4 p-6 shadow-2xl backdrop-blur-xl md:p-10 lg:p-14"><div className="relative z-10 grid gap-12 lg:grid-cols-[0.9fr_1.4fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/[0.07] px-4 py-2 text-xs font-semibold uppercase tracking-[0.24em] text-emerald-200/80"><span className="h-2 w-2 rounded-full bg-emerald-300"/>{no?"Tilgjengelig for freelance":"Available for freelance"}</div><p className="text-xs uppercase tracking-[0.38em] text-white/40">{no?"Jobb med meg":"Work with me"}</p><h2 className="mt-3 text-4xl font-bold md:text-5xl">{no?"Har du et prosjekt i tankene?":"Have a project in mind?"}</h2><p className="mt-6 max-w-xl text-base leading-relaxed text-white/60 md:text-lg">{no?"Jeg hjelper bedrifter, klubber og privatpersoner med moderne, responsive nettsider — fra design og utvikling til publisering.":"I help businesses, clubs and individuals create modern, responsive websites — from design and development to deployment."}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/Freelance#request" className="rounded-full bg-white px-6 py-3 font-semibold text-black transition hover:scale-105">{no?"Start et prosjekt →":"Start a project →"}</Link><Link href="/Projects" className="rounded-full border border-white/15 bg-white/[0.06] px-6 py-3 font-semibold text-white/75">{no?"Se arbeidet mitt":"See my work"}</Link></div></div><div className="grid gap-3 sm:grid-cols-2">{freelanceServices.map(s=><div key={s.number} className="rounded-3xl border border-white/10 bg-black/25 p-6"><div className="flex justify-between gap-4"><h3 className="text-lg font-bold">{s.title}</h3><span className="text-xs text-white/25">{s.number}</span></div><p className="mt-3 text-sm leading-relaxed text-white/55">{s.text}</p></div>)}</div></div><div className="relative z-10 mt-12 flex flex-wrap items-center gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-xs uppercase tracking-[0.22em] text-white/35"><span>{no?"Snakk sammen":"Discuss"}</span><span>→</span><span>{no?"Design":"Design"}</span><span>→</span><span>{no?"Utvikle":"Develop"}</span><span>→</span><span>{no?"Lansere":"Launch"}</span></div></div></section>
<section className="fade-up mx-auto max-w-7xl px-6 pt-20"><div className="rounded-4xl border border-white/10 bg-white/4 p-6 shadow-2xl backdrop-blur-xl"><div className="scale-95"><Interests/></div></div></section><Contact/></div></main> }
